# Generated by Django 5.1.5 on 2025-01-30 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_resent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
