# Generated by Django 5.1.5 on 2025-01-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification_last_resent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='last_resent_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='resend_count',
        ),
    ]
